### PR TITLE
Improves prompting and changes ID to Serial

### PR DESCRIPTION
**Pull request by Greg-Hawkridge**

### CODE REVIEW

**Comment by tobyaharris** [comment]
Can the script print them in the same order as the user needs to enter them? I think it's different. Looking at the config file:
```
[input.scanner]
serial="0581_011c"
connection_point=["0","1.3.1"]
platform = "fd500000.pcie-pci-0000:01:00.0"
```

PS should these parameters be indented in the config file?

**Comment by tobyaharris** [comment]
I like making the parameter name consistent (ID / serial) however can I suggest we use another word, to avoid confusion with the manufacturer's serial number printed on the physical unit?

**Comment by Greg-Hawkridge** [comment]
> Can the script print them in the same order as the user needs to enter them? I think it's different. At the time of writing the code outputs these in the order
> 
> ```
>     echo -e  "Serial: \t \t \t $ID"
>     echo -e  "Platform: \t \t $platform"
>     echo -e  "Connection Point: \t $connection_port \n"
> ```
> 
> But the config file reads:
> 
> ```
> [input.scanner]
> serial="0581_011c"
> connection_point=["0","1.3.1"]
> platform = "fd500000.pcie-pci-0000:01:00.0"
> ```
> 
> PS should these parameters be indented in the config file?

The change it. 
Indentation doesn't matter in toml files.

> I like making the parameter name consistent (ID / serial) however can I suggest we use another word, to avoid confusion with the manufacturer's serial number printed on the physical unit?

Do that in a future PR - when applying quality of life PRs, it's better to get them out and improve bit by bit with actual feedback than to um and ah about the perfect solution.

**Comment by tobyaharris** [comment]
This now works in my testing
image

As I've made the more recent changes I'll welcome review.

**Review by tobyaharris — APPROVED** [review]

**Pull request merged**
